extends:
  - next/core-web-vitals
  - '@kurone-kito/eslint-config-react'
parserOptions:
  project:
    - './tsconfig.eslint.json'
root: true
rules:
  import/extensions:
    - error
    - never
    - js: ignorePackages
      json: ignorePackages
